# Generated by Django 5.2 on 2025-04-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rajesh', '0002_aboutme_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
