# Generated by Django 5.2 on 2025-04-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rajesh', '0003_delete_aboutme_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='skills/')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(default='about_images/default.jpg', upload_to='about_images/'),
        ),
    ]
