# Generated by Django 5.2 on 2025-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rajesh', '0004_skill_profile_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='aboutDescription',
            field=models.TextField(default='This is my about section.'),
        ),
    ]
