# Generated by Django 5.2 on 2025-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rajesh', '0005_remove_profile_about_image_profile_aboutdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(default='about_images/default.jpg', upload_to='about_images/'),
        ),
    ]
