# Generated by Django 5.2 on 2025-04-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rajesh', '0008_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
