# Generated by Django 5.2 on 2025-04-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rajesh', '0010_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
