# Generated by Django 5.2 on 2025-04-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rajesh', '0011_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
