# Generated by Django 5.2 on 2025-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rajesh', '0013_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='link',
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
